PUT https://coupon-code-gyrovi.herokuapp.com/api/update/coupon
Content-Type: application/json
Accept: application/json

{
"id":"4",
"coupon_code":"CHICKENTANDOORIES1000",
"expiry_date":"2022-06-12 19:00:00",
"type":"percentdiscount",
"discount":"10"
}
